# ------------------------------- configuration for Event -------------------------------------#
particle_types:
  digis:
    amount: 'digi_nDigis'
    branches:
      wh: 'digi_wheel'
      sc: 'digi_sector'
      st: 'digi_station'
      sl: 'digi_superLayer'
      w: 'digi_wire'
      l: 'digi_layer'
      time: 'digi_time'
    attributes:
      BX:
        expr: 'int(time // 25) if time is not None else None'
    sorter:
      by: 'p.BX'
  emushowers:
    amount: 'ph2Shower_station'
    branches:
      wh: 'ph2Shower_wheel'
      sc : 'ph2Shower_sector'
      st: 'ph2Shower_station'
      sl: 'ph2Shower_superlayer'
      nDigis: 'ph2Shower_ndigis'
      BX: 'ph2Shower_BX'
      min_wire: 'ph2Shower_min_wire'
      max_wire: 'ph2Shower_max_wire'
      avg_pos: 'ph2Shower_avg_pos'
      avg_time: 'ph2Shower_avg_time'
      wires_profile: 'ph2Shower_wires_profile'

# -------------------------------- configuration for NTuple --------------------------------------#
ntuple_tree_name: '/dtNtupleProducer/DTTREE'

# ------------------------------- configuration for dt plots  -------------------------------------#
dt_plots_configs:
  mplhep-style: 'CMS'         # Style to use for the plots

  figure-configs: 
    figure.dpi: 100             # Dots per inch (resolution)
    axes.titlesize: 'small'     # Axes title size
    axes.labelsize: 'x-small'    # Axes label size
    xtick.labelsize: 'x-small'    # X-axis tick label size
    ytick.labelsize: 'x-small'    # Y-axis tick label size
    legend.fontsize: 'small'   # Legend font size

  dt-cell-info:
    particle_type: 'digis'      # Particle type to use
    cmap_var: 'time'            # Variable to use for the colormap

  cmap-configs:
    cmap: 'viridis'             # Colormap to use
    cmap_under: 'none'          # Color for values under vmin
    norm:
      class: 'matplotlib.colors.Normalize'  # Normalization class
      vmin: 299                             # Minimum value for normalization
      vmax: 1000                            # Maximum value for normalization

  # DT bounds and cells are matplotlib.patches.Rectangle objects
  bounds-kwargs:
    facecolor: ["lightgray", "lightyellow", "lightpink", "lightblue"]   # Color of the rectangle [MB, SL1, SL3, SL2]
    edgecolor: "k"                                                      # Color of the edge
    alpha: 0.3                                                          # Transparency of the rectangle
    linewidth: 0.5                                                      # Width of the edge

  cells-kwargs:
    edgecolor: "k"              # Color of the edge
    linewidth: 0.025              # Width of the edge
