# -------------------------------- configuration for NTuples --------------------------------------#
# source of the ntuple class to use
# comment/uncomment as needed, only one should be active
ntuple_source: 'src.ntuples.dtntuple.DtNtuple'
# ntuple_source: 'src.ntuples.g4dt_ntuple.G4DtNtuple'

ntuple_params:
  # define here posible parameters to use when process the events in the ntuple
  genmuon-showered-method: 2
  shower-threshold: 6

ntuple_selectors:
  # define the selectors to be used in the ntuple, always use at least no_filter
  # comment/uncomment/add as needed...
  # - "src.utils.filters.base_filters.no_filter"
  # ================= available selectors - dtntuple ================= #
  - "src.utils.filters.base_filters.baseline"
  # - "src.utils.filters.base_filters.removeShower"
  # - "src.utils.filters.base_filters.baseline_plus_hitsc"
  # ================= available selectors - g4ntuple ================= #
  # - ...
# ------------------------------- configuration for particles -------------------------------------#

particle_types:
  # particles to be built into an event from .root files
  # follow the format:
  #
  #   particle_name:
  #     class: 'path.to.particle.Particle'
  #     n_branch_name:  ROOT.TBranch (int) that could define how many particles to build
  #     conditioner: condition to filter the particles that want to be built
  #     sorter: how to sort the particles
  #       by: 'property' to sort by
  #       reverse: True/False to sort in reverse order
  #
  # comment/uncomment/add as needed...
  # ================= available particles - dtntuple ================= #
  digis:
    class: 'dtpr.particles.digi.Digi'
    n_branch_name: 'digi_nDigis'
    sorter:
      by: 'BX'
  segments:
    class: 'dtpr.particles.segment.Segment'
    n_branch_name: 'seg_nSegments'
  tps:
    class: 'dtpr.particles.ph2tp.Ph2tp'
    n_branch_name: 'ph2TpgPhiEmuAm_nTrigs'
  genmuons:
    class: 'dtpr.particles.gen_muon.GenMuon'
    n_branch_name: 'gen_nGenParts'
    conditioner: 
      property: 'gen_pdgId'
      condition: "==13"
    sorter:
      by: 'pt'
      reverse: True
  # emushowers:
  #   class: 'dtpr.particles.shower.Shower'
  #   n_branch_name: 'ph2Shower_station'
  simhits:
    class: 'dtpr.particles.simhit.SimHit'
    n_branch_name: 'simHit_nSimHits'
  # ================= available particles - g4ntuple ================= #
  # digis:
  #   class: 'src.utils.particles.g4digi.G4Digi'
  #   n_branch_name: 'nSLHit_NHits'
  #   sorter:
  #     by: 'BX'
  # simhits:
  #   class: 'src.utils.particles.g4digi.G4Digi'
  #   n_branch_name: 'nSLHit_NHits'
  #   sorter:
  #     by: 'BX'

# -------------------------------- configuration for histograms -----------------------------------#
histo_sources:
  # define the source modules of the histograms
  - src.utils.histograms.baseHistos
  - src.utils.histograms.am_histos
  - src.utils.histograms.digi_histos
  - src.utils.histograms.shower_histos

histo_names:
  # Histogram to fill - Uncomment or add histograms as needed. 
  # They should exist in any of the source modules
  # # ============ efficiencies ============ #
  - seg_eff_MB1
  - seg_eff_MB2
  - seg_eff_MB3
  - seg_eff_MB4
  - fwshower_eff_MB1
  - fwshower_eff_MB2
  - fwshower_eff_MB3
  - fwshower_eff_MB4
  # # ------ conf maps------
  # - shower_tpfptnfn_MB1
  # - shower_tpfptnfn_MB2
  # - shower_tpfptnfn_MB3
  # - shower_tpfptnfn_MB4
  # - shower_tpfptnfn_g4
  # # ============== rates =============== #
  # - AM_rate_allBX_MB1
  # - AM_rate_allBX_MB2
  # - AM_rate_allBX_MB3
  # - AM_rate_allBX_MB4
  # - AM_rate_goodBX_MB1
  # - AM_rate_goodBX_MB2
  # - AM_rate_goodBX_MB3
  # - AM_rate_goodBX_MB4
  # - fwshower_rate_goodBX_MB1
  # - fwshower_rate_goodBX_MB2
  # - fwshower_rate_goodBX_MB3
  # - fwshower_rate_goodBX_MB4
  # - fwshower_rate_allBX_MB1
  # - fwshower_rate_allBX_MB2
  # - fwshower_rate_allBX_MB3
  # - fwshower_rate_allBX_MB4
  # # ============ leading_mu ============ #
  # - LeadingMuon_pt
  # - LeadingMuon_eta
  # - LeadingMuon_maxDPhi
  # - LeadingMuon_maxDEta
  # # =========== subleading_mu ========== #
  # - SubLeadingMuon_pt
  # - SubLeadingMuon_eta
  # - SubLeadingMuon_maxDPhi
  # - SubLeadingMuon_maxDEta
  # # ============= other_vars =========== #
  # - shower_eff_muon_pt
  # - shower_eff_muon_eta
  # - muon_DR
  # - nGenMuons
  # - dphimax_seg_showering_muon
  # - dphimax_seg_non_showering_muon
  # - dphimax_tp_showering_muon
  # - dphimax_tp_non_showering_muon
  # - dphi_seg_showering_muon
  # - dphi_seg_non_showering_muon
  # - dphi_tp_showering_muon
  # - dphi_tp_non_showering_muon
  # # =========== digis =========== #
  # - digi_w_gmts_MB1
  # - digi_w_gmts_MB2
  # - digi_w_gmts_MB3
  # - digi_w_gmts_MB4
  # - digi_w_gmtns_MB1
  # - digi_w_gmtns_MB2
  # - digi_w_gmtns_MB3
  # - digi_w_gmtns_MB4
  # - digi_wd_gmts_MB1
  # - digi_wd_gmts_MB2
  # - digi_wd_gmts_MB3
  # - digi_wd_gmts_MB4
  # - digi_wd_gmtns_MB1
  # - digi_wd_gmtns_MB2
  # - digi_wd_gmtns_MB3
  # - digi_wd_gmtns_MB4
  # - digi_wl_gmts_MB1
  # - digi_wl_gmts_MB2
  # - digi_wl_gmts_MB3
  # - digi_wl_gmts_MB4
  # - digi_wl3d_gmts_MB1
  # - digi_wl3d_gmts_MB2
  # - digi_wl3d_gmts_MB3
  # - digi_wl3d_gmts_MB4
  # - digi_wl_gmtns_MB1
  # - digi_wl_gmtns_MB2
  # - digi_wl_gmtns_MB3
  # - digi_wl_gmtns_MB4
  # - digi_wl3d_gmtns_MB1
  # - digi_wl3d_gmtns_MB2
  # - digi_wl3d_gmtns_MB3
  # - digi_wl3d_gmtns_MB4


# ------------------------------- configuration for dt plots  -------------------------------------#
dt_plots_configs:
  mplhep-style: 'CMS'         # Style to use for the plots

  figure-configs: 
    figure.dpi: 100             # Dots per inch (resolution)
    axes.titlesize: 'small'     # Axes title size
    axes.labelsize: 'x-small'    # Axes label size
    xtick.labelsize: 'x-small'    # X-axis tick label size
    ytick.labelsize: 'x-small'    # Y-axis tick label size
    legend.fontsize: 'small'   # Legend font size

  dt-cell-info:
    particle_type: 'digis'      # Particle type to use
    cmap_var: 'time'            # Variable to use for the colormap

  cmap-configs:
    cmap: 'viridis'             # Colormap to use
    cmap_under: 'none'          # Color for values under vmin
    norm:
      class: 'matplotlib.colors.Normalize'  # Normalization class
      vmin: 299                             # Minimum value for normalization
      vmax: 1000                            # Maximum value for normalization

  # DT bounds and cells are matplotlib.patches.Rectangle objects
  bounds-kwargs:
    facecolor: ["lightgray", "lightyellow", "lightpink", "lightblue"]   # Color of the rectangle [MB, SL1, SL3, SL2]
    edgecolor: "k"                                                      # Color of the edge
    alpha: 0.3                                                          # Transparency of the rectangle

  cells-kwargs:
    edgecolor: "k"              # Color of the edge
