name: Python CI

on:
  push:
    branches: [main, destrada-dtpr]
  pull_request:
    branches: [main, destrada-dtpr]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install black only
        run: poetry add --group dev black

      - name: Check code formatting with black
        run: poetry run black --check -l 100 dtpr.

  pytest:
  # Use a pre-built Docker container with ROOT and Python pre-installed.
  # This simplifies the setup and ensures a consistent environment.
  runs-on: ubuntu-latest
  needs: black
  container:
    image: cern/root:6.26.06-python3.9
  # The entrypoint is set to avoid potential issues with Poetry
  # and the container's default setup.
  options: --entrypoint=/bin/bash

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Python and ROOT are already available in the container
    # No need for separate setup steps.

    - name: Install Poetry
      run: |
        pip install poetry
      shell: bash

    - name: Install project dependencies
      run: |
        poetry install
      shell: bash

    - name: Run tests with pytest
      run: poetry run pytest
      shell: bash
