name: Python CI

on:
  push:
    branches:
      - main
    paths:
      - 'dtpr/**'
  pull_request:
    branches:
      - main
    paths:
      - 'dtpr/**'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3

      - name: Install black only
        run: poetry add --group dev black

      - name: Check code formatting with black
        run: poetry run black --check -l 100 dtpr

  pytest: # NEED TO BE FIXED - DISABLE AT THE MOMENT
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ROOT
        run: |
          sudo apt update
          sudo apt install -y binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev libxext-dev libxft-dev libxpm-dev python3 libtbb-dev libvdt-dev libgif-dev
          wget https://root.cern/download/root_v6.32.16.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
          tar -xzvf root_v6.32.16.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
          source root/bin/thisroot.sh >> .bashrc
          python -c "import ROOT; print(ROOT.__version__)"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install project dependencies
        run: pip install . && pip install pytest

      - name: Run tests with pytest
        run: pytest
